addons:
  sonarqube: true
language: java
jdk:
  - oraclejdk8
  - openjdk10
env:
  global:
    - CODECOV_TOKEN=ce3ce570-c4f3-4c2c-8dc2-7e537ed3a752
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew javadoc
  - sonar-scanner