language: java
jdk:
  - oraclejdk8
env:
  global:
    - CODECOV_TOKEN=ce3ce570-c4f3-4c2c-8dc2-7e537ed3a752
script:
  - ./gradlew test
  - ./gradlew integrationTest
after_success:
  - bash <(curl -s https://codecov.io/bash)

